### ISSUE TITLE
Certificate expired 9th of Dec

### ISSUE THREAD

**Issue by joltcan** [CodeRelease/CodeRelease#13]
The certificate on https://coderelease.io/ that is.

**Comment by antoniotajuelo** [comment]
Fixed! Thx for notifying!

**Comment by joltcan** [comment]
Thanks for a great service!


> On 12 Dec 2019, at 17:17, Antonio Tajuelo <notifications@github.com> wrote:
> 
> Fixed! Thx for notifying!
> 
> 

-- 
Fredrik Lundhag
