### ISSUE TITLE
Repository listet but not available

### ISSUE THREAD

**Issue by FrankGiesecke** [CodeRelease/CodeRelease#2]
I've stared the repository heroku/cli (https://github.com/heroku/cli) which contains more than 600 releases and gets updates in a very short cycle.

After logging in to coderelease.io using my GitHub login, the repository is listet.
It's also possible to select the repository for getting notified.

But when I select the repository link (https://coderelease.io/github/repository/heroku/cli) on coderelease.io I see an error page.

<img width="672" alt="404" src="https://user-images.githubusercontent.com/4430040/44570531-75456480-a77e-11e8-9ee1-789c45b2a1fe.png">

**Comment by antoniotajuelo** [comment]
Hi, thanks for reporting.

A small issue has been fixed and this is working now :)
