### ISSUE TITLE
Stopped receiving updates a week ago?

### ISSUE THREAD

**Issue by hikerspath** [CodeRelease/CodeRelease#3]
While I see my subscriptions active in your UI, I stopped receiving updates about a week ago?  Anything wrong on your end?

**Comment by hikerspath** [comment]
If it helps, the last release I saw was for terraform-providers/terraform-provider-aws v1.32.0 which was sent out on the 17th of August.  I have checked my spam and other possible causes.

**Comment by antoniotajuelo** [comment]
Thx for your feedback.

Found the email in the log. It was actually delivered into your email provider, but somehow it didn't show up in your inbox.

Subject was this:
📩 terraform-providers/terraform-provider-aws v1.33.0 released

In case this happens again please reopen the issue.
