### ISSUE TITLE
Emails go into void

### ISSUE THREAD

**Issue by jens1o** [CodeRelease/CodeRelease#4]
![image](https://user-images.githubusercontent.com/11234139/44848651-e5108f00-ac57-11e8-8496-89b25241633d.png)

I do not receive any emails although I hve set up multiple mail accounts. :/

**Comment by hikerspath** [comment]
I had same issue here...  https://github.com/CodeRelease/CodeRelease/issues/3 and it happened again this morning :-)

**Comment by antoniotajuelo** [comment]
@jens1o Just added the option for editing the email address, after you log in with Github. Now you can change it.

**Comment by antoniotajuelo** [comment]
@hikerspath What repo notification are you missing this morning?

**Comment by hikerspath** [comment]
Reference missing alert
```
Yelp/elastalert
 Latest Release: v0.1.35, 1 day ago  Just updated
```

All seems to be well this morning though (not sure if you guys did anything?)

![coderelease-emails](https://user-images.githubusercontent.com/8323388/44936797-21b9b480-ad44-11e8-9b17-da11ff81e6fe.png)

Above was with the following search in gMail...
```
from:no-reply@coderelease.io in:anywhere
```

**Comment by antoniotajuelo** [comment]
Not any changes. v1.33.0 notification was actually sent but blocked by Gmail at some point.

Thanks for the additional feedback Brian!

**Comment by TroudhuK** [comment]
I often lose notifications too, the last one is `Aris-t2/CustomCSSforFx 2.1.6 released`, and I don't have the next releases, or other notifications (hotmail.fr address).
