### ISSUE TITLE
Subscriptions management privacy/security issue

### ISSUE THREAD

**Issue by piotr-tobolski** [CodeRelease/CodeRelease#6]
Email notification link shows notification management for the wrong user.

I have notifications set up for 2 email accounts, e.g. email1 and email2.
I set some notifications to email1 and later email2.
I received notification on email1, clicked the link to manage them and... email2 management appeared. Like the web browser remembered last used email address in cookies. I tried to click the link again while verifying the recipient email address but the effect was the same. When I used the option to log out and then clicked the link the account I was managing became correct one.

I didn't try it but it looks like privacy/security issue. I assume that I can enter any email address into the form, then click my link and see what notifications this person is subscribed to and manage them.

**Comment by antoniotajuelo** [comment]
Hi, thanks for opening the issue.

The notification management link will log in you only if you are not already logged in into a different account. In the example you are sharing, it seems that before anything you are already logged in into email2. That's the reason why when you click on the link for email1, email2's subscriptions are displayed.

Does it make sense? How do you think this should be managed?

**Comment by piotr-tobolski** [comment]
The question is - how was I logged in as email2? I never got any notification to email2 so I had no way of logging in. It looks like setting up a subscription automatically logged me in.

**Comment by antoniotajuelo** [comment]
May you have been previously login with Github?

At the moment, the only 2 ways for log in are login with Github and the "manage subscription" link in the emails.

In case you didn't login with Github, please send me the emails using the contact form for getting more details and clarifying this case: https://coderelease.io/contact

**Comment by antoniotajuelo** [comment]
Hi again,
The details you provided have been very helpful and the issue has been located and fixed.
Your guess was totally correct: when a subscription was being created via form and the user account was created (when needed), the user was being logged in. This has been fixed.
Big thanks for reporting this issue and helping for solving it.
