### ISSUE TITLE
Slow emails or none at all.

### ISSUE THREAD

**Issue by asyba** [CodeRelease/CodeRelease#9]
Why some times there are no emails notification?
I have many new releases but no emails.
![screenshot from 2018-11-28 12-00-12](https://user-images.githubusercontent.com/1466530/49160288-34bd3000-f305-11e8-8030-522e40e19ed3.png)

**Comment by antoniotajuelo** [comment]
Please check the subscription level by clicking on the Edit blue link on each subscription, and adjust the level to the proper one.

--
Sonríe a la vida

2018/11/28 16:01、Federico <notifications@github.com>のメール:

**Comment by asyba** [comment]
Okay will check that, just in case I will set all to be "All Releases (+ Prerel.) " I guess any type of releases will get notify right?
